<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>Sunshine</RootNamespace>
    <AssemblyName>Sunshine</AssemblyName>

    <!-- Keep it light: framework-dependent (reuses the installed .NET runtime instead of bundling one). -->
    <SelfContained>false</SelfContained>
    <TieredPGO>true</TieredPGO>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\app.ico" />
    <Resource Include="Assets\app_icon.png" />
  </ItemGroup>

</Project>
